environment:
  LOG_DESTINATIONS: '[{"papertrail":{"token":"gvXu8cxW2wujpERxoT1wLrXe"}}]'
packages:
  - name: joke
    actions:
      - name: joke
        runtime: "python:default"
  - name: main
    environment:
      LOG_DESTINATIONS: '[{"papertrail":{"token":"gvXu8cxW2wujpERxoT1wLrXe"}}]'
    actions:
      - name: main
        runtime: "python:default"
      - name: MorningMessage
        runtime: "python:default"
      - name: TallyFormSubmit
        runtime: "python:default"
