packages:
  - name: joke
    environment: LOG_DESTINATIONS:'[{"logtail":{"token":"gvXu8cxW2wujpERxoT1wLrXe"}}]'
    actions:
      - name: joke
        runtime: "python:default"
  - name: main
    actions:
      - name: main
        runtime: "python:default"
      - name: MorningMessage
        runtime: "python:default"
      - name: TallyFormSubmit
        runtime: "python:default"
